version: "3.9"

services:
  api:
    build:
      context: ./services/api
    container_name: readholdings-api-dev
    environment:
      - NODE_ENV=production
      # elastic
      - ELASTICSEARCH_NODES
      - ELASTICSEARCH_PORT
      - ELASTICSEARCH_USERNAME
      - ELASTICSEARCH_PASSWORD
      - INSU_APIKEY
      - INSU_CUSTID
      - INSMI_APIKEY
      - INSMI_CUSTID
      - INSHS_APIKEY
      - INSHS_CUSTID
      - INS2I_APIKEY
      - INS2I_CUSTID
      - INSB_APIKEY
      - INSB_CUSTID
      - INC_APIKEY
      - INC_CUSTID
      - INEE_APIKEY
      - INEE_CUSTID
      - INSIS_APIKEY
      - INSIS_CUSTID
      - INP_APIKEY
      - INP_CUSTID
      - IN2P3_APIKEY
      - IN2P3_CUSTID
      - INTEST_APIKEY
      - INTEST_CUSTID
    command: "npm start"
    ports:
      - ${API_PORT:-59701}:3000
    depends_on:
      elastic:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -Y off --no-verbose --tries=1 --spider http://localhost:3000/healthcheck || exit 1"
        ]
      interval: 10s
      timeout: 10s
      retries: 5
  
  frontend:
    build:
      context: ./services/frontend
    container_name: readholdings-frontend-dev
    ports:
      - ${FRONTEND_PORT:-59706}:3000
      - 24678:24678
    environment:
      - NODE_ENV
      - NUXT_PUBLIC_ENVIRONMENT
      - NUXT_PUBLIC_ELASTIC_ENV
      - NUXT_PUBLIC_VERSION
      - NUXT_PUBLIC_API_URL
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -Y off --no-verbose --tries=1 --spider http://localhost:3000 || exit 1"
        ]
      interval: 10s
      timeout: 10s
      retries: 5

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.22
    container_name: readholdings-elastic-dev
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - ES_JAVA_OPTS=-Xms4g -Xmx4g
      - ELASTIC_USERNAME={ELASTICSEARCH_USERNAME:-elastic}
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
    volumes:
      - "./data/elastic:/usr/share/elasticsearch/data"
    ports:
      - 9200:9200
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --fail http://elastic:changeme@localhost:9200"
        ]
      interval: 10s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.22
    container_name: readholdings-kibana-dev
    environment:
      - ELASTICSEARCH_HOSTS="http://elastic:9200"
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
      - xpack.security.enabled=true
    depends_on:
      elastic:
        condition: service_healthy
    ports:
      - 5601:5601
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --fail http://elastic:changeme@localhost:5601/api/status"
        ]
      interval: 10s
      timeout: 10s
      retries: 5
