version: "3.9"

services:
  api:
    image: node:22.4
    container_name: readholdings-api-dev
    environment:
      - NODE_ENV
      # smtp
      - SMTP_HOST=maildev
      - SMTP_PORT
      # mail
      - NOTIFICATIONS_SENDER
      - NOTIFICATIONS_RECEIVERS
      - NOTIFICATIONS_MACHINE
      # elastic
      - ELASTICSEARCH_NODES
      - ELASTICSEARCH_PORT
      - ELASTICSEARCH_USERNAME
      - ELASTICSEARCH_PASSWORD
      # redis
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
      # Ebsco
      - INSU_APIKEY
      - INSU_CUSTID
      - INSMI_APIKEY
      - INSMI_CUSTID
      - INSHS_APIKEY
      - INSHS_CUSTID
      - INS2I_APIKEY
      - INS2I_CUSTID
      - INSB_APIKEY
      - INSB_CUSTID
      - INC_APIKEY
      - INC_CUSTID
      - INEE_APIKEY
      - INEE_CUSTID
      - INSIS_APIKEY
      - INSIS_CUSTID
      - INP_APIKEY
      - INP_CUSTID
      - IN2P3_APIKEY
      - IN2P3_CUSTID
      - INTEST_APIKEY
      - INTEST_CUSTID
      # cron
      - CRON_CLEAN_FILE_SCHEDULE
      - CRON_CLEAN_FILE_ACTIVE
      - CRON_CLEAN_LOG_APPLICATION_THRESHOLD
      - CRON_CLEAN_LOG_ACCESS_THRESHOLD
      - CRON_CLEAN_LOG_HEALTHCHECK_THRESHOLD
      - CRON_CLEAN_HOLDINGSIQ_THRESHOLD
      - CRON_CLEAN_HLM_THRESHOLD
      - CRON_DATA_UPDATE_SCHEDULE
      - CRON_DATA_UPDATE_ACTIVE

    working_dir: /usr/src/app
    volumes:
      - ./services/api:/usr/src/app
    command: "npm run dev"
    ports:
      - ${API_PORT:-59701}:3000
    depends_on:
      elastic:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -Y off --no-verbose --tries=1 --spider http://localhost:3000/healthcheck || exit 1"
        ]
      interval: 10s
      timeout: 10s
      retries: 5
  
  redis:
    image: redis:7.2.4
    container_name: readholdings-redis-dev
    command: redis-server --requirepass "${REDIS_PASSWORD:-changeme}"
    volumes:
      - ${REDIS_DATA_PATH:-./data/redis}:/data
    ports:
      - ${REDIS_PORT:-6379}:6379
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "redis-cli --pass changeme ping | grep PONG"
        ]
      interval: 10s
      timeout: 3s
      retries: 5
  
  frontend:
    image: node:22.4
    container_name: readholdings-frontend-dev
    working_dir: /usr/src/app
    volumes:
      - ./services/frontend:/usr/src/app
    command: "npm run dev"
    ports:
      - ${FRONTEND_PORT:-59706}:3000
      - 24678:24678
    environment:
      - NODE_ENV
      - HOST=0.0.0.0
      - NUXT_PUBLIC_ENVIRONMENT=development
      - NUXT_PUBLIC_ELASTIC_ENV=development
      - NUXT_PUBLIC_VERSION=development
      - NUXT_PUBLIC_API_HOST
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -Y off --no-verbose --tries=1 --spider http://localhost:3000 || exit 1"
        ]
      interval: 10s
      timeout: 10s
      retries: 5

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.22
    container_name: readholdings-elastic-dev
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - ES_JAVA_OPTS=-Xms4g -Xmx4g
      - ELASTIC_USERNAME={ELASTICSEARCH_USERNAME:-elastic}
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
    volumes:
      - "./data/elastic:/usr/share/elasticsearch/data"
    ports:
      - 9200:9200
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --fail http://elastic:changeme@localhost:9200"
        ]
      interval: 10s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.22
    container_name: readholdings-kibana-dev
    environment:
      - ELASTICSEARCH_HOSTS="http://elastic:9200"
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
      - XPACK_SECURITY_ENABLED=true
      - XPACK.REPORTING.ROLES.ENABLED=false
      - XPACK_REPORTING_MAXCONCURRENTEXPORTS=5
      - XPACK_REPORTING_CSV_MAXSIZEBYTES=3221225472
      - XPACK_REPORTING_QUEUE_TIMEOUT=1800000
      - ELASTICSEARCH_SETTING_kibana.autocompleteTimeout=300000
    ports:
      - 5601:5601
    restart: unless-stopped
    depends_on:
      elastic:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --fail http://elastic:changeme@localhost:5601/api/status"
        ]
      interval: 10s
      timeout: 10s
      retries: 5

  maildev:
    image: djfarrelly/maildev
    container_name: readholdings-maildev-dev
    ports:
      - 1080:80
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -Y off --no-verbose --tries=1 --spider http://localhost:80 || exit 1"
        ]
      interval: 10s
      timeout: 10s
      retries: 5
